dist: trusty
language: rust
services: docker
sudo: required
rust: stable
env:
  global:
  - CRATE_NAME=stest
  - DEPLOY_VERSION=stable
  - TARGET=x86_64-unknown-linux-gnu
matrix:
  exclude:
  - language: rust
  include:
  - env: TARGET=i686-unknown-linux-gnu
  - env: TARGET=i686-unknown-linux-musl
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=i686-apple-darwin
    os: osx
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=aarch64-unknown-linux-gnu
  - env: TARGET=armv7-unknown-linux-gnueabihf
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: NJchlGr+lfi0VEfq2EFXpHi86o5nSWNyCLCEz2qSmrADcJxyGOljVOrgv35JGc3jUE/jTmb9cRdiT67flHIfQg/yQEhfRbofzcGXcTZxPnNcIPjLWBcQREk/EiBUWbWOCEy4arLTrx7INVDsf8AdaRxv4HTXTZ3s4N6zFrJ/mAdYIbyMmqBhZd/Gb25AlLkk+qRTH0hfWTHfVCapav7GWQLAht183PUtwduqHKvMkfpuW79rXRbdwewwmyWODTSd9ck0e3CwQ+jDxffLh5a4/ZIrFLED9AqsS7veqz+Q+LSHis0uPecn0safxjD7aLQJi3fgADyuqjy9TP7hdXbm1lPkfGNTBg3WoWuYwWmHNX/6slWSuqvhTtUTQV7fQe5AOUFTVpmFA4LZXQgs8gxcudAb0CdTZVTXMJnPCN8EKMuO07748S+YUGScStMVttgi36k7U6LsGX1wqwk0ki9FcYplCziWL+7nWKs6jW7rirUXS1xQWbwvHzLDWYR2PMZhxPGRZlSZNEHQOm33caCnirxRo2R+2XcogES68McWVgc2Odec/UbZyZzOS8a3X14WNYIV1xaa2kIDhxnDUnOV2mDupgabqJjgjohoL7TxYY2zo/guV3akQ9uKHk1CI/wvDdNR/GdaNEcfPtpFl6E5wTw721JsaZQrh4JDhPZEocM=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = $DEPLOY_VERSION"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
