dist: trusty
language: rust
services: docker
sudo: required

# TODO This is the Rust channel that build jobs will use by default but can be
# overridden on a case by case basis down below
rust: stable

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=stest

    # TODO This is the channel that will be used to produce binary releases
    - DEPLOY_VERSION=stable

    # default job
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  exclude:
    - language: rust
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Other architectures
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=armv7-unknown-linux-gnueabihf
      #- env: TARGET=mips-unknown-linux-gnu
      #- env: TARGET=mips64-unknown-linux-gnuabi64
      #- env: TARGET=mips64el-unknown-linux-gnuabi64
      #- env: TARGET=mipsel-unknown-linux-gnu
      #- env: TARGET=powerpc-unknown-linux-gnu
      #- env: TARGET=powerpc64-unknown-linux-gnu
      #- env: TARGET=powerpc64le-unknown-linux-gnu
      #- env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt GH_TOKEN=0123456789012345678901234567890123456789`
  # - Paste the output down here
  api_key:
    secure: HnhtXz54KUAwtAQF4+PbyhdxYCvBkW3J9pimSOmPRsuq64ljzYthC3jZcmWxm3gAD+/tjejRYesqOA05m7Gw0lc/VDJy8vNul7OlF52UOR+4wOSkINh+26WfGXRZmEUIby0ZQ10LLvBjMdvLPQQNydkuSx2Gh9y11yorO1+uHjATy5sxrBUOtoKNwNDcl5LFvojvhcw7m4YTAt49t3SUA5O40e3HgaHmDabRkGHROU7P2NHhLBUvppmXilAf4VlszIdW7PlPJ0bwE69mL6xD9H2u3KOJ0z3iRxU9S3hiOEE0QPiHXxBCXhaCu0OAifedgncWfV6qGzFnP6OWiJ4X5MCj2tuogwq4MhfD+uFojthCjXNuozQ8QZ/BnOwYWELb5dG9eJL/dvD78cbsZlHS1+8YZ1U4d2zLS4YCwSGBu/xtoGx1WhxS7XMZgivFMD5TFmTGhDKTQJkGc3E4hWRW0dgzQAiFngtlyRRl+wEWS0wZkyFuo2J3oYBlTWI/rzSMDFWSTe2SSc9VCF5jM8c+ofu3daVxalZS5wwTk74w0C4M26LABG4wuSbbXpfI++rIntjXWbrnHQvccKacfDZaEm+j50aZ0rCbMBQpZSZ57OBPl/JwZN7YIQm0bwfdDqRfvlRFfMSSqkDxLWMqKwGcNtdUbTTNxLEKEJwRDs9n6po=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = $DEPLOY_VERSION
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
