dist: trusty
language: rust
services: docker
sudo: required
rust: stable
env:
  global:
  - CRATE_NAME=stest
  - DEPLOY_VERSION=stable
  - TARGET=x86_64-unknown-linux-gnu
  - secure: OLYbvtgexBn3ZoVymjLcxw1Dx5LzH4QA2LTYFna0LueF9A910EnNE+IpWByM3gYSK1T4vMqmfuOPLxRl6eigCgT3ZKi31FJjNa1AYdkUnqfAx78g/Sbu9gpG4hcUao2SgEryAA84bYaruZpcG2IIVB3I9BuGWJt0ZNP8KNoDokhbCWa9xaKURja3QF5hUKbLMvUjbsgIaJvRIN4dU0pnSheds2g/8CBGujGgW1yl2aEYkPm6XgPUGo4WewCxWXdfDTxff/rzo4Vr6Lc7wy1VZrVnG3qAh2sDKcnmVbqOxb+qyYeHse5q8BsegEydIcJqCJGVNf1ofaq59H/YjmXx/Fe1D/UtR9BE5eijVMAramOLuFcpWOAJmnsXqWlYsAJl1Rm2RFtNYDBR/6oEB0UQzn49KsSc+5MfxDmExM6Tn2UiJyaYWMYwdCwBDxBx5q4v0BxNEM6zLAQ/sdWIiQmtX4TY2l9OyAnXZe0e6/qRlJ7Lz3moK4HQNM4KbnazZnadoltx8Z6fRjFe2BtGUz1A/UyvDkx0+TxB7gKf1XartU9muqA+rqJj27/awxZDIFW5MNjqLMCipRwS39n/q1vxdz5lzLJ3rVZOzTZ8HSIpHrdccpVgAcNxLmDLeqpVnOiSFcPwOViCz6MVw2csizUnucoFofKSG0SXc8LQPuTAcJI=
matrix:
  exclude:
  - language: rust
  include:
  - env: TARGET=i686-unknown-linux-gnu
  - env: TARGET=i686-unknown-linux-musl
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=i686-apple-darwin
    os: osx
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=aarch64-unknown-linux-gnu
  - env: TARGET=armv7-unknown-linux-gnueabihf
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: OLYbvtgexBn3ZoVymjLcxw1Dx5LzH4QA2LTYFna0LueF9A910EnNE+IpWByM3gYSK1T4vMqmfuOPLxRl6eigCgT3ZKi31FJjNa1AYdkUnqfAx78g/Sbu9gpG4hcUao2SgEryAA84bYaruZpcG2IIVB3I9BuGWJt0ZNP8KNoDokhbCWa9xaKURja3QF5hUKbLMvUjbsgIaJvRIN4dU0pnSheds2g/8CBGujGgW1yl2aEYkPm6XgPUGo4WewCxWXdfDTxff/rzo4Vr6Lc7wy1VZrVnG3qAh2sDKcnmVbqOxb+qyYeHse5q8BsegEydIcJqCJGVNf1ofaq59H/YjmXx/Fe1D/UtR9BE5eijVMAramOLuFcpWOAJmnsXqWlYsAJl1Rm2RFtNYDBR/6oEB0UQzn49KsSc+5MfxDmExM6Tn2UiJyaYWMYwdCwBDxBx5q4v0BxNEM6zLAQ/sdWIiQmtX4TY2l9OyAnXZe0e6/qRlJ7Lz3moK4HQNM4KbnazZnadoltx8Z6fRjFe2BtGUz1A/UyvDkx0+TxB7gKf1XartU9muqA+rqJj27/awxZDIFW5MNjqLMCipRwS39n/q1vxdz5lzLJ3rVZOzTZ8HSIpHrdccpVgAcNxLmDLeqpVnOiSFcPwOViCz6MVw2csizUnucoFofKSG0SXc8LQPuTAcJI=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = $DEPLOY_VERSION"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
